version: "3"

services:
  agro_book:
    build:
      context: "."
      args:
        APP_PORT: "8080"
        APP_HOST: "0.0.0.0"
    command: python3 /opt/app/manage.py
    ports:
      - "8080:8080"