version: "3"

services:

  redis:
    image: redis
  
  link_cheker_server:
    build:
      context: "server/"
    links:
       - redis
    environment:
      SERVER_PORT: "8081"
      SERVER_HOST: "0.0.0.0"
      DEBUG: "True"
      CLIENT_PORT: "8000"
      CLIENT_HOST: "0.0.0.0"
      REDIS_URL: "redis"
    command: "gunicorn --chdir /opt/app/server/ manage:run --bind localhost:8081 --worker-class aiohttp.GunicornWebWorker"
    ports:
      - "8081:8081"
  
  link_cheker_client:
    build:
      context: "client/"
    environment:
      CLIENT_PORT: "8000"
      CLIENT_HOST: "0.0.0.0"
      DEBUG: "True"
    command: 'python3 /opt/app/client/app.py'
    ports:
      - "8000:8000"

